server:
  port: 8080
  servlet:
    context-path: /bookswap

spring:
  application:
    name: BookSwap
    
  datasource:
    url: jdbc:postgresql://localhost:5432/bookswap_db
    username: bookswap_user
    password: bookswap_password
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: openid,email,profile
            
  web:
    resources:
      static-locations: classpath:/static/
      
logging:
  level:
    com.bookswap: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/bookswap.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

# API конфигурация для внешнего сервиса
external-api:
  books:
    base-url: https://www.googleapis.com/books/v1
    timeout: 5000
  currency:
    base-url: https://api.exchangerate-api.com/v4/latest
    timeout: 3000 